# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
	${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "hectronic-x86"
BBFILE_PATTERN_hectronic-x86 := "^${LAYERDIR}/"
BBFILE_PRIORITY_hectronic-x86 = "9"

LAYERDEPENDS_hectronic-x86 = "core intel"
LAYERSERIES_COMPAT_hectronic-x86 = "wrynose" 
LAYERVERSION_hectronic-x86 = "1"

